"""Create POI, User, Alert, Route tables

Revision ID: 21383f3ecfa5
Revises: 58760e21b00b
Create Date: 2025-07-16 02:22:20.409143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21383f3ecfa5'
down_revision: Union[str, Sequence[str], None] = '58760e21b00b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
